TITLE BURBLE SORT EN ENSAMBLADOR, VERSION 1
.MODEL SMALL
.STACK 100H
.DATA  
    ARRAY DB 10,9,8,7,6,5,4,3,2,1 
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX   
    ;IMPLEMENTACION DE BURBLE SORT
    ;SI, ES MI INDICADOR I
    XOR SI,SI 
    ;SE REALIZA  SIZE -1 VECES
    MOV CX,9 
CICLO1:
    ; DI ES MI INDICE J, SE HACE IGUal a I+1
    MOV DI,SI
    INC DI
    ;CX CONTROLA  AMBOS CICLOS, POR ESO LO METO A LA PILA
    PUSH CX
CICLO2:
    MOV AL, ARRAY[SI]
    CMP AL, ARRAY[DI]
    ;SI ES MENOR O IGUAL, YA ESTA ORDENADO
    JLE NEXT 
INTERCAMBIA:
    MOV AL,ARRAY[SI]
    XCHG AL,ARRAY[DI]
    MOV ARRAY[SI],AL
NEXT:
    INC DI 
    LOOP CICLO2
    POP CX
    INC SI
    LOOP CICLO1

    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN
